name: Y tế Công cộng
description: Gieo sức khỏe - Gặt niềm tin
meta_description: "Nghiên cứu khoa học - Khoa học sức khỏe - Dịch tễ học - Y tế Công cộng - Thống kê - Việt Nam"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
# , jekyll-archives]
baseurl: /
domain_name: 'www.ytecongcong.com'
google_analytics: 'UA-83930831-1'
disqus: true
disqus_shortname: 'ytecongcong'
# disqus_shortname: 'khoe-vi-nuoc'

# Details for the RSS feed generator
url:            'http://www.ytecongcong.com'
author:         'Y tế Công cộng'
# authorTwitter:  'fieuvan'
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234

paginate: 7
permalink:       /:year/:title/
mathjax: true # whether support mathjax
safe: false

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
